[package]
edition = "2024"
name    = "sandbox"
version = "0.1.0"

[dependencies]
derive_more = { version = "2.0.1", features = [ "full" ] }
ggmath      = { path = "../ggmath", features = [ "full" ] }
#newnum      = "0.0.9"
