[package]
categories = [
    "data-structures",
    "game-development",
    "graphics",
    "mathematics",
]
description = "optimized generic-graphics-math"
edition = "2024"
license = "MIT"
name = "ggmath"
readme = "../README.md"
repository = "https://github.com/Noam2Stein/ggmath"
version = "0.6.0"

[features]
default = [ "matrix", "newnum", "primitive_aliases", "quaternion" ]

matrix            = [  ]
primitive_aliases = [  ]
quaternion        = [  ]

full = [
    "matrix",
    "newnum",
    "primitive_aliases",
    "quaternion",
    "rectangle",
    "testing",
]

rectangle = [  ]
testing   = [  ]

[dependencies]
derive-where       = "1.2.7"
ggmath_proc_macros = "0.6.0"
newnum             = { version = "0.0.12", optional = true, public = true }
splat_attribs      = "1.0.0"
