[package]
description = "optimized generic-graphics-math"
edition     = "2021"
license     = "MIT"
name        = "ggmath"
readme      = "../README.md"
version     = "0.1.2"

[features]
default = [ "matrix", "primitive_aliases", "quaternion" ]

matrix            = [  ]
primitive_aliases = [  ]
quaternion        = [  ]

full = [
    "line",
    "matrix",
    "primitive_aliases",
    "quaternion",
    "ray",
    "rectangle",
]

line      = [  ]
ray       = [  ]
rectangle = [  ]

[dependencies]
ggmath_proc_macros = "0.1.1"
num-traits         = "0.2.19"

[dev-dependencies]
ggmath_testing = { path = "../testing" }
