[package]
categories = [
    "data-structures",
    "game-development",
    "graphics",
    "mathematics",
]
description = "optimized generic-graphics-math"
edition = "2024"
license = "MIT"
name = "ggmath"
readme = "../README.md"
repository = "https://github.com/Noam2Stein/ggmath"
version = "0.9.0"

[features]
default = [ "matrix", "primitive_aliases", "quaternion" ]

matrix            = [  ]
primitive_aliases = [  ]
quaternion        = [  ]
rectangle         = [  ]
testing           = [  ]

full = [ "matrix", "primitive_aliases", "quaternion", "rectangle", "testing" ]

positive_backward = [  ]
positive_down     = [  ]
positive_forward  = [  ]
positive_left     = [  ]
positive_right    = [  ]
positive_up       = [  ]

[dependencies]
derive-where  = "1.2.7"
macro_loop    = "0.4.1"
splat_attribs = "1.0.0"

crevice = { version = "0.18.0", optional = true }
