[package]
categories = [
    "data-structures",
    "game-development",
    "graphics",
    "mathematics",
]
description = "optimized generic-graphics-math"
edition = "2024"
license = "MIT"
name = "ggmath"
readme = "../README.md"
repository = "https://github.com/Noam2Stein/ggmath"
version = "0.5.0"

[features]
default = [ "matrix", "num", "primitive_aliases", "quaternion" ]

matrix            = [  ]
num               = [ "dep:newnum" ]
primitive_aliases = [  ]
quaternion        = [  ]

full = [
    "matrix",
    "num",
    "primitive_aliases",
    "quaternion",
    "rectangle",
    "testing",
]

rectangle = [ "num" ]
testing   = [  ]

[dependencies]
ggmath_proc_macros = "0.5.0"
newnum             = { path = "../../newnum/newnum", optional = true }
splat_attribs      = "1.0.0"
