[package]
categories = [
    "data-structures",
    "game-development",
    "graphics",
    "mathematics",
]
description = "optimized generic-graphics-math"
edition = "2021"
license = "MIT"
name = "ggmath"
readme = "../README.md"
repository = "https://github.com/Noam2Stein/ggmath"
version = "0.3.0"

[features]
default = [ "matrix", "primitive_aliases", "quaternion" ]

matrix            = [  ]
primitive_aliases = [  ]
quaternion        = [  ]

full = [
    "matrix",
    "primitive_aliases",
    "quaternion",

    "line",
    "ray",
    "rectangle",

    "testing",
]

line      = [  ]
ray       = [  ]
rectangle = [  ]

testing = [  ]

[dependencies]
ggmath_proc_macros = { path = "../ggmath_proc_macros" }
num-traits         = "0.2.19"
