[package]
edition = "2021"
name = "ggmath"
version = "0.1.0"

[features]
default = ["primitive_aliases", "matrix", "quaternion"]
full = ["primitive_aliases", "matrix", "quaternion", "rect", "line", "ray"]

primitive_aliases = []
matrix = []
quaternion = []
rect = []
line = []
ray = []

[dependencies]
ggmath_proc_macros = { path = "../proc_macros" }
