// This file was generated by a codegen tool.
// To modify this file, modify the source code of the codegen tool.

use ggmath::*;

#[test]
fn test_simd_primitive_fns() {
    assert_eq!(
        Vec2::from_array([1isize, 2isize]).as_array(),
        [1isize, 2isize]
    );
    assert_eq!(
        Vec3::from_array([1isize, 2isize, 3isize]).as_array(),
        [1isize, 2isize, 3isize]
    );
    assert_eq!(
        Vec4::from_array([1isize, 2isize, 3isize, 4isize]).as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(Vec2::splat(1isize).as_array(), [1isize; 2]);
    assert_eq!(Vec3::splat(1isize).as_array(), [1isize; 3]);
    assert_eq!(Vec4::splat(1isize).as_array(), [1isize; 4]);

    assert_eq!(
        Vec2::from_fn(|i| [1isize, 2isize][i]).as_array(),
        [1isize, 2isize]
    );
    assert_eq!(
        Vec3::from_fn(|i| [1isize, 2isize, 3isize][i]).as_array(),
        [1isize, 2isize, 3isize]
    );
    assert_eq!(
        Vec4::from_fn(|i| [1isize, 2isize, 3isize, 4isize][i]).as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(
        Vec2::const_from_array([1isize, 2isize]).as_array(),
        [1isize, 2isize]
    );
    assert_eq!(
        Vec3::const_from_array([1isize, 2isize, 3isize]).as_array(),
        [1isize, 2isize, 3isize]
    );
    assert_eq!(
        Vec4::const_from_array([1isize, 2isize, 3isize, 4isize]).as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(vec2!(1isize, 2isize).as_array(), [1isize, 2isize]);
    assert_eq!(vec2!(vec2!(1isize, 2isize)).as_array(), [1isize, 2isize]);
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).as_array(),
        [1isize, 2isize, 3isize]
    );
    assert_eq!(
        vec3!(1isize, vec2!(2isize, 3isize)).as_array(),
        [1isize, 2isize, 3isize]
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );
    assert_eq!(
        vec4!(1isize, vec2!(2isize, 3isize), 4isize).as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );
    assert_eq!(
        vec4!(
            1isize,
            vec2!(2isize, 3isize),
            Vector::<1, isize, Simd>::from_array([4isize])
        )
        .as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(vec2!(1isize, 2isize).as_array_ref(), &[1isize, 2isize]);
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).as_array_ref(),
        &[1isize, 2isize, 3isize]
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).as_array_ref(),
        &[1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(vec2!(1isize, 2isize).as_mut_array(), &mut [1isize, 2isize]);
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).as_mut_array(),
        &mut [1isize, 2isize, 3isize]
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).as_mut_array(),
        &mut [1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(vec2!(1isize, 2isize).as_simd(), vec2!(1isize, 2isize));
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).as_simd(),
        vec3!(1isize, 2isize, 3isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).as_simd(),
        vec4!(1isize, 2isize, 3isize, 4isize)
    );

    assert_eq!(vec2!(1isize, 2isize).as_nonsimd(), vec2s!(1isize, 2isize));
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).as_nonsimd(),
        vec3s!(1isize, 2isize, 3isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).as_nonsimd(),
        vec4s!(1isize, 2isize, 3isize, 4isize)
    );

    assert_eq!(vec2!(1isize, 2isize).len(), 2);
    assert_eq!(vec3!(1isize, 2isize, 3isize).len(), 3);
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).len(), 4);

    assert_eq!(vec2!(1isize, 2isize).is_simd(), true);
    assert_eq!(vec3!(1isize, 2isize, 3isize).is_simd(), true);
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).is_simd(), true);

    assert_eq!(vec2!(1isize, 2isize).get(0), Some(1isize));
    assert_eq!(vec2!(1isize, 2isize).get(1), Some(2isize));
    assert_eq!(vec2!(1isize, 2isize).get(2), None);
    assert_eq!(vec2!(1isize, 2isize).get(3), None);

    assert_eq!(vec3!(1isize, 2isize, 3isize).get(0), Some(1isize));
    assert_eq!(vec3!(1isize, 2isize, 3isize).get(1), Some(2isize));
    assert_eq!(vec3!(1isize, 2isize, 3isize).get(2), Some(3isize));
    assert_eq!(vec3!(1isize, 2isize, 3isize).get(3), None);
    assert_eq!(vec3!(1isize, 2isize, 3isize).get(4), None);

    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).get(0), Some(1isize));
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).get(1), Some(2isize));
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).get(2), Some(3isize));
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).get(3), Some(4isize));
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).get(4), None);
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).get(5), None);

    assert_eq!(vec2!(1isize, 2isize).get_mut(0), Some(&mut 1isize));
    assert_eq!(vec2!(1isize, 2isize).get_mut(1), Some(&mut 2isize));
    assert_eq!(vec2!(1isize, 2isize).get_mut(2), None);
    assert_eq!(vec2!(1isize, 2isize).get_mut(3), None);

    assert_eq!(vec3!(1isize, 2isize, 3isize).get_mut(0), Some(&mut 1isize));
    assert_eq!(vec3!(1isize, 2isize, 3isize).get_mut(1), Some(&mut 2isize));
    assert_eq!(vec3!(1isize, 2isize, 3isize).get_mut(2), Some(&mut 3isize));
    assert_eq!(vec3!(1isize, 2isize, 3isize).get_mut(3), None);
    assert_eq!(vec3!(1isize, 2isize, 3isize).get_mut(4), None);

    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_mut(0),
        Some(&mut 1isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_mut(1),
        Some(&mut 2isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_mut(2),
        Some(&mut 3isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_mut(3),
        Some(&mut 4isize)
    );
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).get_mut(4), None);
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).get_mut(5), None);

    unsafe {
        assert_eq!(vec2!(1isize, 2isize).get_unchecked(0), 1isize);
        assert_eq!(vec2!(1isize, 2isize).get_unchecked(1), 2isize);

        assert_eq!(vec3!(1isize, 2isize, 3isize).get_unchecked(0), 1isize);
        assert_eq!(vec3!(1isize, 2isize, 3isize).get_unchecked(1), 2isize);
        assert_eq!(vec3!(1isize, 2isize, 3isize).get_unchecked(2), 3isize);

        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).get_unchecked(0),
            1isize
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).get_unchecked(1),
            2isize
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).get_unchecked(2),
            3isize
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).get_unchecked(3),
            4isize
        );

        assert_eq!(vec2!(1isize, 2isize).get_unchecked_mut(0), &mut 1isize);
        assert_eq!(vec2!(1isize, 2isize).get_unchecked_mut(1), &mut 2isize);

        assert_eq!(
            vec3!(1isize, 2isize, 3isize).get_unchecked_mut(0),
            &mut 1isize
        );
        assert_eq!(
            vec3!(1isize, 2isize, 3isize).get_unchecked_mut(1),
            &mut 2isize
        );
        assert_eq!(
            vec3!(1isize, 2isize, 3isize).get_unchecked_mut(2),
            &mut 3isize
        );

        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).get_unchecked_mut(0),
            &mut 1isize
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).get_unchecked_mut(1),
            &mut 2isize
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).get_unchecked_mut(2),
            &mut 3isize
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).get_unchecked_mut(3),
            &mut 4isize
        );
    }

    assert_eq!(
        vec2!(1isize, 2isize).iter().collect::<Vec<isize>>(),
        vec![1isize, 2isize]
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).iter().collect::<Vec<isize>>(),
        vec![1isize, 2isize, 3isize]
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize)
            .iter()
            .collect::<Vec<isize>>(),
        vec![1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(
        vec2!(1isize, 2isize)
            .iter_mut()
            .collect::<Vec<&mut isize>>(),
        vec![&mut 1isize, &mut 2isize]
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize)
            .iter_mut()
            .collect::<Vec<&mut isize>>(),
        vec![&mut 1isize, &mut 2isize, &mut 3isize]
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize)
            .iter_mut()
            .collect::<Vec<&mut isize>>(),
        vec![&mut 1isize, &mut 2isize, &mut 3isize, &mut 4isize]
    );

    assert_eq!(
        vec2!(1isize, 2isize).map(|x| x == 2isize),
        vec2!(false, true)
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).map(|x| x == 2isize),
        vec3!(false, true, false)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).map(|x| x == 2isize),
        vec4!(false, true, false, false)
    );

    assert_eq!(
        vec2!(1isize, 2isize).zip(vec2!(2isize, 1isize)),
        vec2!((1isize, 2isize), (2isize, 1isize))
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).zip(vec3!(2isize, 3isize, 1isize)),
        vec3!((1isize, 2isize), (2isize, 3isize), (3isize, 1isize))
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).zip(vec4!(2isize, 3isize, 4isize, 1isize)),
        vec4!(
            (1isize, 2isize),
            (2isize, 3isize),
            (3isize, 4isize),
            (4isize, 1isize)
        )
    );

    assert_eq!(vec2!(1isize, 2isize).reverse(), vec2!(2isize, 1isize));
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).reverse(),
        vec3!(3isize, 2isize, 1isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).reverse(),
        vec4!(4isize, 3isize, 2isize, 1isize)
    );

    assert_eq!(
        vec2!(1isize, 2isize).get_const_vec2::<0, 1>(),
        vec2!(1isize, 2isize)
    );
    assert_eq!(
        vec2!(1isize, 2isize).get_const_vec2::<1, 0>(),
        vec2!(2isize, 1isize)
    );
    assert_eq!(
        vec2!(1isize, 2isize).get_const_vec2::<1, 1>(),
        vec2!(2isize, 2isize)
    );

    assert_eq!(
        vec3!(1isize, 2isize, 3isize).get_const_vec2::<0, 1>(),
        vec2!(1isize, 2isize)
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).get_const_vec2::<0, 2>(),
        vec2!(1isize, 3isize)
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).get_const_vec2::<2, 1>(),
        vec2!(3isize, 2isize)
    );

    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_const_vec2::<0, 1>(),
        vec2!(1isize, 2isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_const_vec2::<1, 3>(),
        vec2!(2isize, 4isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_const_vec2::<3, 1>(),
        vec2!(4isize, 2isize)
    );

    assert_eq!(
        vec2!(1isize, 2isize).get_const_vec3::<0, 1, 1>(),
        vec3!(1isize, 2isize, 2isize)
    );
    assert_eq!(
        vec2!(1isize, 2isize).get_const_vec3::<1, 0, 1>(),
        vec3!(2isize, 1isize, 2isize)
    );

    assert_eq!(
        vec3!(1isize, 2isize, 3isize).get_const_vec3::<0, 1, 2>(),
        vec3!(1isize, 2isize, 3isize)
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).get_const_vec3::<1, 0, 2>(),
        vec3!(2isize, 1isize, 3isize)
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).get_const_vec3::<2, 1, 0>(),
        vec3!(3isize, 2isize, 1isize)
    );

    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_const_vec3::<0, 1, 2>(),
        vec3!(1isize, 2isize, 3isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_const_vec3::<1, 0, 2>(),
        vec3!(2isize, 1isize, 3isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_const_vec3::<2, 1, 0>(),
        vec3!(3isize, 2isize, 1isize)
    );

    assert_eq!(
        vec2!(1isize, 2isize).get_const_vec4::<0, 1, 1, 0>(),
        vec4!(1isize, 2isize, 2isize, 1isize)
    );
    assert_eq!(
        vec2!(1isize, 2isize).get_const_vec4::<1, 0, 1, 0>(),
        vec4!(2isize, 1isize, 2isize, 1isize)
    );
    assert_eq!(
        vec2!(1isize, 2isize).get_const_vec4::<1, 1, 0, 0>(),
        vec4!(2isize, 2isize, 1isize, 1isize)
    );

    assert_eq!(
        vec3!(1isize, 2isize, 3isize).get_const_vec4::<0, 1, 2, 0>(),
        vec4!(1isize, 2isize, 3isize, 1isize)
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).get_const_vec4::<1, 0, 2, 0>(),
        vec4!(2isize, 1isize, 3isize, 1isize)
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize).get_const_vec4::<2, 1, 0, 0>(),
        vec4!(3isize, 2isize, 1isize, 1isize)
    );

    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_const_vec4::<0, 1, 2, 3>(),
        vec4!(1isize, 2isize, 3isize, 4isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_const_vec4::<1, 0, 2, 3>(),
        vec4!(2isize, 1isize, 3isize, 4isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_const_vec4::<2, 1, 0, 3>(),
        vec4!(3isize, 2isize, 1isize, 4isize)
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).get_const_vec4::<3, 1, 2, 0>(),
        vec4!(4isize, 2isize, 3isize, 1isize)
    );

    assert_eq!(vec2!(1isize, 2isize)[0], 1isize);
    assert_eq!(vec2!(1isize, 2isize)[1], 2isize);

    assert_eq!(vec3!(1isize, 2isize, 3isize)[0], 1isize);
    assert_eq!(vec3!(1isize, 2isize, 3isize)[1], 2isize);
    assert_eq!(vec3!(1isize, 2isize, 3isize)[2], 3isize);

    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize)[0], 1isize);
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize)[1], 2isize);
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize)[2], 3isize);
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize)[3], 4isize);

    assert_eq!(&mut vec2!(1isize, 2isize)[0], &mut 1isize);
    assert_eq!(&mut vec2!(1isize, 2isize)[1], &mut 2isize);

    assert_eq!(&mut vec3!(1isize, 2isize, 3isize)[0], &mut 1isize);
    assert_eq!(&mut vec3!(1isize, 2isize, 3isize)[1], &mut 2isize);
    assert_eq!(&mut vec3!(1isize, 2isize, 3isize)[2], &mut 3isize);

    assert_eq!(&mut vec4!(1isize, 2isize, 3isize, 4isize)[0], &mut 1isize);
    assert_eq!(&mut vec4!(1isize, 2isize, 3isize, 4isize)[1], &mut 2isize);
    assert_eq!(&mut vec4!(1isize, 2isize, 3isize, 4isize)[2], &mut 3isize);
    assert_eq!(&mut vec4!(1isize, 2isize, 3isize, 4isize)[3], &mut 4isize);

    assert_eq!(vec2!(1isize, 2isize) == vec2!(1isize, 2isize), true);
    assert_eq!(vec2!(1isize, 2isize) == vec2!(2isize, 1isize), false);
    assert_eq!(vec2!(1isize, 2isize) == vec2!(2isize, 2isize), false);

    assert_eq!(
        vec3!(1isize, 2isize, 3isize) == vec3!(1isize, 2isize, 3isize),
        true
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize) == vec3!(4isize, 3isize, 2isize),
        false
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize) == vec3!(2isize, 2isize, 3isize),
        false
    );

    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize) == vec4!(1isize, 2isize, 3isize, 4isize),
        true
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize) == vec4!(4isize, 3isize, 2isize, 1isize),
        false
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize) == vec4!(2isize, 2isize, 2isize, 4isize),
        false
    );

    assert_eq!(vec2!(1isize, 2isize) != vec2!(1isize, 2isize), false);
    assert_eq!(vec2!(1isize, 2isize) != vec2!(2isize, 1isize), true);
    assert_eq!(vec2!(1isize, 2isize) != vec2!(2isize, 2isize), true);

    assert_eq!(
        vec3!(1isize, 2isize, 3isize) != vec3!(1isize, 2isize, 3isize),
        false
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize) != vec3!(4isize, 3isize, 2isize),
        true
    );
    assert_eq!(
        vec3!(1isize, 2isize, 3isize) != vec3!(2isize, 2isize, 3isize),
        true
    );

    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize) != vec4!(1isize, 2isize, 3isize, 4isize),
        false
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize) != vec4!(4isize, 3isize, 2isize, 1isize),
        true
    );
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize) != vec4!(2isize, 2isize, 2isize, 4isize),
        true
    );

    assert_eq!(vec2!(1isize, 2isize).to_string(), "(1, 2)");
    assert_eq!(vec3!(1isize, 2isize, 3isize).to_string(), "(1, 2, 3)");
    assert_eq!(
        vec4!(1isize, 2isize, 3isize, 4isize).to_string(),
        "(1, 2, 3, 4)"
    );

    assert_eq!(format!("{:?}", vec2!(1isize, 2isize)), "(1, 2)");
    assert_eq!(format!("{:?}", vec3!(1isize, 2isize, 3isize)), "(1, 2, 3)");
    assert_eq!(
        format!("{:?}", vec4!(1isize, 2isize, 3isize, 4isize)),
        "(1, 2, 3, 4)"
    );

    assert_eq!(vec2!(1isize, 2isize).x, 1isize);
    assert_eq!(vec2!(1isize, 2isize).y, 2isize);

    assert_eq!(vec3!(1isize, 2isize, 3isize).x, 1isize);
    assert_eq!(vec3!(1isize, 2isize, 3isize).y, 2isize);
    assert_eq!(vec3!(1isize, 2isize, 3isize).z, 3isize);

    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).x, 1isize);
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).y, 2isize);
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).z, 3isize);
    assert_eq!(vec4!(1isize, 2isize, 3isize, 4isize).w, 4isize);

    assert_eq!(&mut vec2!(1isize, 2isize).x, &mut 1isize);
    assert_eq!(&mut vec2!(1isize, 2isize).y, &mut 2isize);

    assert_eq!(&mut vec3!(1isize, 2isize, 3isize).x, &mut 1isize);
    assert_eq!(&mut vec3!(1isize, 2isize, 3isize).y, &mut 2isize);
    assert_eq!(&mut vec3!(1isize, 2isize, 3isize).z, &mut 3isize);

    assert_eq!(&mut vec4!(1isize, 2isize, 3isize, 4isize).x, &mut 1isize);
    assert_eq!(&mut vec4!(1isize, 2isize, 3isize, 4isize).y, &mut 2isize);
    assert_eq!(&mut vec4!(1isize, 2isize, 3isize, 4isize).z, &mut 3isize);
    assert_eq!(&mut vec4!(1isize, 2isize, 3isize, 4isize).w, &mut 4isize);

    #[cfg(feature = "swizzle")]
    {
        assert_eq!(vec2!(1isize, 2isize).xy(), vec2!(1isize, 2isize));
        assert_eq!(vec2!(1isize, 2isize).yx(), vec2!(2isize, 1isize));
        assert_eq!(vec2!(1isize, 2isize).yy(), vec2!(2isize, 2isize));

        assert_eq!(vec3!(1isize, 2isize, 3isize).xy(), vec2!(1isize, 2isize));
        assert_eq!(vec3!(1isize, 2isize, 3isize).xz(), vec2!(1isize, 3isize));
        assert_eq!(vec3!(1isize, 2isize, 3isize).zy(), vec2!(3isize, 2isize));

        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).xy(),
            vec2!(1isize, 2isize)
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).yw(),
            vec2!(2isize, 4isize)
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).wy(),
            vec2!(4isize, 2isize)
        );

        assert_eq!(vec2!(1isize, 2isize).xyy(), vec3!(1isize, 2isize, 2isize));
        assert_eq!(vec2!(1isize, 2isize).yxy(), vec3!(2isize, 1isize, 2isize));

        assert_eq!(
            vec3!(1isize, 2isize, 3isize).xyz(),
            vec3!(1isize, 2isize, 3isize)
        );
        assert_eq!(
            vec3!(1isize, 2isize, 3isize).yxz(),
            vec3!(2isize, 1isize, 3isize)
        );
        assert_eq!(
            vec3!(1isize, 2isize, 3isize).zyx(),
            vec3!(3isize, 2isize, 1isize)
        );

        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).xyz(),
            vec3!(1isize, 2isize, 3isize)
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).yxz(),
            vec3!(2isize, 1isize, 3isize)
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).zyx(),
            vec3!(3isize, 2isize, 1isize)
        );

        assert_eq!(
            vec2!(1isize, 2isize).xyyx(),
            vec4!(1isize, 2isize, 2isize, 1isize)
        );
        assert_eq!(
            vec2!(1isize, 2isize).yxyx(),
            vec4!(2isize, 1isize, 2isize, 1isize)
        );
        assert_eq!(
            vec2!(1isize, 2isize).yyxx(),
            vec4!(2isize, 2isize, 1isize, 1isize)
        );

        assert_eq!(
            vec3!(1isize, 2isize, 3isize).xyzx(),
            vec4!(1isize, 2isize, 3isize, 1isize)
        );
        assert_eq!(
            vec3!(1isize, 2isize, 3isize).yxzx(),
            vec4!(2isize, 1isize, 3isize, 1isize)
        );
        assert_eq!(
            vec3!(1isize, 2isize, 3isize).zyxx(),
            vec4!(3isize, 2isize, 1isize, 1isize)
        );

        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).xyzw(),
            vec4!(1isize, 2isize, 3isize, 4isize)
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).yxzw(),
            vec4!(2isize, 1isize, 3isize, 4isize)
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).zyxw(),
            vec4!(3isize, 2isize, 1isize, 4isize)
        );
        assert_eq!(
            vec4!(1isize, 2isize, 3isize, 4isize).wyzx(),
            vec4!(4isize, 2isize, 3isize, 1isize)
        );
    }
}

#[test]
#[should_panic]
fn test_vec2_index_panic() {
    vec2!(1isize, 2isize)[2];
}

#[test]
#[should_panic]
fn test_vec3_index_panic() {
    vec3!(1isize, 2isize, 3isize)[3];
}

#[test]
#[should_panic]
fn test_vec4_index_panic() {
    vec4!(1isize, 2isize, 3isize, 4isize)[4];
}

#[test]
fn test_nonsimd_primitive_fns() {
    assert_eq!(size_of::<Vec2S<isize>>(), size_of::<isize>() * 2);
    assert_eq!(size_of::<Vec3S<isize>>(), size_of::<isize>() * 3);
    assert_eq!(size_of::<Vec4S<isize>>(), size_of::<isize>() * 4);

    assert_eq!(align_of::<Vec2S<isize>>(), align_of::<isize>());
    assert_eq!(align_of::<Vec3S<isize>>(), align_of::<isize>());
    assert_eq!(align_of::<Vec4S<isize>>(), align_of::<isize>());

    assert_eq!(
        Vec2S::from_array([1isize, 2isize]).as_array(),
        [1isize, 2isize]
    );
    assert_eq!(
        Vec3S::from_array([1isize, 2isize, 3isize]).as_array(),
        [1isize, 2isize, 3isize]
    );
    assert_eq!(
        Vec4S::from_array([1isize, 2isize, 3isize, 4isize]).as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(Vec2S::splat(1isize).as_array(), [1isize; 2]);
    assert_eq!(Vec3S::splat(1isize).as_array(), [1isize; 3]);
    assert_eq!(Vec4S::splat(1isize).as_array(), [1isize; 4]);

    assert_eq!(
        Vec2S::from_fn(|i| [1isize, 2isize][i]).as_array(),
        [1isize, 2isize]
    );
    assert_eq!(
        Vec3S::from_fn(|i| [1isize, 2isize, 3isize][i]).as_array(),
        [1isize, 2isize, 3isize]
    );
    assert_eq!(
        Vec4S::from_fn(|i| [1isize, 2isize, 3isize, 4isize][i]).as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(
        Vec2S::const_from_array([1isize, 2isize]).as_array(),
        [1isize, 2isize]
    );
    assert_eq!(
        Vec3S::const_from_array([1isize, 2isize, 3isize]).as_array(),
        [1isize, 2isize, 3isize]
    );
    assert_eq!(
        Vec4S::const_from_array([1isize, 2isize, 3isize, 4isize]).as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(vec2s!(1isize, 2isize).as_array(), [1isize, 2isize]);
    assert_eq!(vec2s!(vec2s!(1isize, 2isize)).as_array(), [1isize, 2isize]);
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).as_array(),
        [1isize, 2isize, 3isize]
    );
    assert_eq!(
        vec3s!(1isize, vec2s!(2isize, 3isize)).as_array(),
        [1isize, 2isize, 3isize]
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );
    assert_eq!(
        vec4s!(1isize, vec2s!(2isize, 3isize), 4isize).as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );
    assert_eq!(
        vec4s!(
            1isize,
            vec2s!(2isize, 3isize),
            Vector::<1, isize, NonSimd>::from_array([4isize])
        )
        .as_array(),
        [1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(vec2s!(1isize, 2isize).as_array_ref(), &[1isize, 2isize]);
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).as_array_ref(),
        &[1isize, 2isize, 3isize]
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).as_array_ref(),
        &[1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(vec2s!(1isize, 2isize).as_mut_array(), &mut [1isize, 2isize]);
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).as_mut_array(),
        &mut [1isize, 2isize, 3isize]
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).as_mut_array(),
        &mut [1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(vec2s!(1isize, 2isize).as_simd(), vec2!(1isize, 2isize));
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).as_simd(),
        vec3!(1isize, 2isize, 3isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).as_simd(),
        vec4!(1isize, 2isize, 3isize, 4isize)
    );

    assert_eq!(vec2s!(1isize, 2isize).as_nonsimd(), vec2s!(1isize, 2isize));
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).as_nonsimd(),
        vec3s!(1isize, 2isize, 3isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).as_nonsimd(),
        vec4s!(1isize, 2isize, 3isize, 4isize)
    );

    assert_eq!(vec2s!(1isize, 2isize).len(), 2);
    assert_eq!(vec3s!(1isize, 2isize, 3isize).len(), 3);
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).len(), 4);

    assert_eq!(vec2s!(1isize, 2isize).is_simd(), false);
    assert_eq!(vec3s!(1isize, 2isize, 3isize).is_simd(), false);
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).is_simd(), false);

    assert_eq!(vec2s!(1isize, 2isize).get(0), Some(1isize));
    assert_eq!(vec2s!(1isize, 2isize).get(1), Some(2isize));
    assert_eq!(vec2s!(1isize, 2isize).get(2), None);
    assert_eq!(vec2s!(1isize, 2isize).get(3), None);

    assert_eq!(vec3s!(1isize, 2isize, 3isize).get(0), Some(1isize));
    assert_eq!(vec3s!(1isize, 2isize, 3isize).get(1), Some(2isize));
    assert_eq!(vec3s!(1isize, 2isize, 3isize).get(2), Some(3isize));
    assert_eq!(vec3s!(1isize, 2isize, 3isize).get(3), None);
    assert_eq!(vec3s!(1isize, 2isize, 3isize).get(4), None);

    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).get(0), Some(1isize));
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).get(1), Some(2isize));
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).get(2), Some(3isize));
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).get(3), Some(4isize));
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).get(4), None);
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).get(5), None);

    assert_eq!(vec2s!(1isize, 2isize).get_mut(0), Some(&mut 1isize));
    assert_eq!(vec2s!(1isize, 2isize).get_mut(1), Some(&mut 2isize));
    assert_eq!(vec2s!(1isize, 2isize).get_mut(2), None);
    assert_eq!(vec2s!(1isize, 2isize).get_mut(3), None);

    assert_eq!(vec3s!(1isize, 2isize, 3isize).get_mut(0), Some(&mut 1isize));
    assert_eq!(vec3s!(1isize, 2isize, 3isize).get_mut(1), Some(&mut 2isize));
    assert_eq!(vec3s!(1isize, 2isize, 3isize).get_mut(2), Some(&mut 3isize));
    assert_eq!(vec3s!(1isize, 2isize, 3isize).get_mut(3), None);
    assert_eq!(vec3s!(1isize, 2isize, 3isize).get_mut(4), None);

    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_mut(0),
        Some(&mut 1isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_mut(1),
        Some(&mut 2isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_mut(2),
        Some(&mut 3isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_mut(3),
        Some(&mut 4isize)
    );
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).get_mut(4), None);
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).get_mut(5), None);

    unsafe {
        assert_eq!(vec2s!(1isize, 2isize).get_unchecked(0), 1isize);
        assert_eq!(vec2s!(1isize, 2isize).get_unchecked(1), 2isize);

        assert_eq!(vec3s!(1isize, 2isize, 3isize).get_unchecked(0), 1isize);
        assert_eq!(vec3s!(1isize, 2isize, 3isize).get_unchecked(1), 2isize);
        assert_eq!(vec3s!(1isize, 2isize, 3isize).get_unchecked(2), 3isize);

        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).get_unchecked(0),
            1isize
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).get_unchecked(1),
            2isize
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).get_unchecked(2),
            3isize
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).get_unchecked(3),
            4isize
        );

        assert_eq!(vec2s!(1isize, 2isize).get_unchecked_mut(0), &mut 1isize);
        assert_eq!(vec2s!(1isize, 2isize).get_unchecked_mut(1), &mut 2isize);

        assert_eq!(
            vec3s!(1isize, 2isize, 3isize).get_unchecked_mut(0),
            &mut 1isize
        );
        assert_eq!(
            vec3s!(1isize, 2isize, 3isize).get_unchecked_mut(1),
            &mut 2isize
        );
        assert_eq!(
            vec3s!(1isize, 2isize, 3isize).get_unchecked_mut(2),
            &mut 3isize
        );

        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).get_unchecked_mut(0),
            &mut 1isize
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).get_unchecked_mut(1),
            &mut 2isize
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).get_unchecked_mut(2),
            &mut 3isize
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).get_unchecked_mut(3),
            &mut 4isize
        );
    }

    assert_eq!(
        vec2s!(1isize, 2isize).iter().collect::<Vec<isize>>(),
        vec![1isize, 2isize]
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize)
            .iter()
            .collect::<Vec<isize>>(),
        vec![1isize, 2isize, 3isize]
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize)
            .iter()
            .collect::<Vec<isize>>(),
        vec![1isize, 2isize, 3isize, 4isize]
    );

    assert_eq!(
        vec2s!(1isize, 2isize)
            .iter_mut()
            .collect::<Vec<&mut isize>>(),
        vec![&mut 1isize, &mut 2isize]
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize)
            .iter_mut()
            .collect::<Vec<&mut isize>>(),
        vec![&mut 1isize, &mut 2isize, &mut 3isize]
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize)
            .iter_mut()
            .collect::<Vec<&mut isize>>(),
        vec![&mut 1isize, &mut 2isize, &mut 3isize, &mut 4isize]
    );

    assert_eq!(
        vec2s!(1isize, 2isize).map(|x| x == 2isize),
        vec2s!(false, true)
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).map(|x| x == 2isize),
        vec3s!(false, true, false)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).map(|x| x == 2isize),
        vec4s!(false, true, false, false)
    );

    assert_eq!(
        vec2s!(1isize, 2isize).zip(vec2s!(2isize, 1isize)),
        vec2s!((1isize, 2isize), (2isize, 1isize))
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).zip(vec3s!(2isize, 3isize, 1isize)),
        vec3s!((1isize, 2isize), (2isize, 3isize), (3isize, 1isize))
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).zip(vec4s!(2isize, 3isize, 4isize, 1isize)),
        vec4s!(
            (1isize, 2isize),
            (2isize, 3isize),
            (3isize, 4isize),
            (4isize, 1isize)
        )
    );

    assert_eq!(vec2s!(1isize, 2isize).reverse(), vec2s!(2isize, 1isize));
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).reverse(),
        vec3s!(3isize, 2isize, 1isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).reverse(),
        vec4s!(4isize, 3isize, 2isize, 1isize)
    );

    assert_eq!(
        vec2s!(1isize, 2isize).get_const_vec2::<0, 1>(),
        vec2s!(1isize, 2isize)
    );
    assert_eq!(
        vec2s!(1isize, 2isize).get_const_vec2::<1, 0>(),
        vec2s!(2isize, 1isize)
    );
    assert_eq!(
        vec2s!(1isize, 2isize).get_const_vec2::<1, 1>(),
        vec2s!(2isize, 2isize)
    );

    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).get_const_vec2::<0, 1>(),
        vec2s!(1isize, 2isize)
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).get_const_vec2::<0, 2>(),
        vec2s!(1isize, 3isize)
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).get_const_vec2::<2, 1>(),
        vec2s!(3isize, 2isize)
    );

    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_const_vec2::<0, 1>(),
        vec2s!(1isize, 2isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_const_vec2::<1, 3>(),
        vec2s!(2isize, 4isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_const_vec2::<3, 1>(),
        vec2s!(4isize, 2isize)
    );

    assert_eq!(
        vec2s!(1isize, 2isize).get_const_vec3::<0, 1, 1>(),
        vec3s!(1isize, 2isize, 2isize)
    );
    assert_eq!(
        vec2s!(1isize, 2isize).get_const_vec3::<1, 0, 1>(),
        vec3s!(2isize, 1isize, 2isize)
    );

    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).get_const_vec3::<0, 1, 2>(),
        vec3s!(1isize, 2isize, 3isize)
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).get_const_vec3::<1, 0, 2>(),
        vec3s!(2isize, 1isize, 3isize)
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).get_const_vec3::<2, 1, 0>(),
        vec3s!(3isize, 2isize, 1isize)
    );

    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_const_vec3::<0, 1, 2>(),
        vec3s!(1isize, 2isize, 3isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_const_vec3::<1, 0, 2>(),
        vec3s!(2isize, 1isize, 3isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_const_vec3::<2, 1, 0>(),
        vec3s!(3isize, 2isize, 1isize)
    );

    assert_eq!(
        vec2s!(1isize, 2isize).get_const_vec4::<0, 1, 1, 0>(),
        vec4s!(1isize, 2isize, 2isize, 1isize)
    );
    assert_eq!(
        vec2s!(1isize, 2isize).get_const_vec4::<1, 0, 1, 0>(),
        vec4s!(2isize, 1isize, 2isize, 1isize)
    );
    assert_eq!(
        vec2s!(1isize, 2isize).get_const_vec4::<1, 1, 0, 0>(),
        vec4s!(2isize, 2isize, 1isize, 1isize)
    );

    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).get_const_vec4::<0, 1, 2, 0>(),
        vec4s!(1isize, 2isize, 3isize, 1isize)
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).get_const_vec4::<1, 0, 2, 0>(),
        vec4s!(2isize, 1isize, 3isize, 1isize)
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize).get_const_vec4::<2, 1, 0, 0>(),
        vec4s!(3isize, 2isize, 1isize, 1isize)
    );

    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_const_vec4::<0, 1, 2, 3>(),
        vec4s!(1isize, 2isize, 3isize, 4isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_const_vec4::<1, 0, 2, 3>(),
        vec4s!(2isize, 1isize, 3isize, 4isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_const_vec4::<2, 1, 0, 3>(),
        vec4s!(3isize, 2isize, 1isize, 4isize)
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).get_const_vec4::<3, 1, 2, 0>(),
        vec4s!(4isize, 2isize, 3isize, 1isize)
    );

    assert_eq!(vec2s!(1isize, 2isize)[0], 1isize);
    assert_eq!(vec2s!(1isize, 2isize)[1], 2isize);

    assert_eq!(vec3s!(1isize, 2isize, 3isize)[0], 1isize);
    assert_eq!(vec3s!(1isize, 2isize, 3isize)[1], 2isize);
    assert_eq!(vec3s!(1isize, 2isize, 3isize)[2], 3isize);

    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize)[0], 1isize);
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize)[1], 2isize);
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize)[2], 3isize);
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize)[3], 4isize);

    assert_eq!(&mut vec2s!(1isize, 2isize)[0], &mut 1isize);
    assert_eq!(&mut vec2s!(1isize, 2isize)[1], &mut 2isize);

    assert_eq!(&mut vec3s!(1isize, 2isize, 3isize)[0], &mut 1isize);
    assert_eq!(&mut vec3s!(1isize, 2isize, 3isize)[1], &mut 2isize);
    assert_eq!(&mut vec3s!(1isize, 2isize, 3isize)[2], &mut 3isize);

    assert_eq!(&mut vec4s!(1isize, 2isize, 3isize, 4isize)[0], &mut 1isize);
    assert_eq!(&mut vec4s!(1isize, 2isize, 3isize, 4isize)[1], &mut 2isize);
    assert_eq!(&mut vec4s!(1isize, 2isize, 3isize, 4isize)[2], &mut 3isize);
    assert_eq!(&mut vec4s!(1isize, 2isize, 3isize, 4isize)[3], &mut 4isize);

    assert_eq!(vec2s!(1isize, 2isize) == vec2s!(1isize, 2isize), true);
    assert_eq!(vec2s!(1isize, 2isize) == vec2s!(2isize, 1isize), false);
    assert_eq!(vec2s!(1isize, 2isize) == vec2s!(2isize, 2isize), false);

    assert_eq!(
        vec3s!(1isize, 2isize, 3isize) == vec3s!(1isize, 2isize, 3isize),
        true
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize) == vec3s!(4isize, 3isize, 2isize),
        false
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize) == vec3s!(2isize, 2isize, 3isize),
        false
    );

    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize) == vec4s!(1isize, 2isize, 3isize, 4isize),
        true
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize) == vec4s!(4isize, 3isize, 2isize, 1isize),
        false
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize) == vec4s!(2isize, 2isize, 2isize, 4isize),
        false
    );

    assert_eq!(vec2s!(1isize, 2isize) != vec2s!(1isize, 2isize), false);
    assert_eq!(vec2s!(1isize, 2isize) != vec2s!(2isize, 1isize), true);
    assert_eq!(vec2s!(1isize, 2isize) != vec2s!(2isize, 2isize), true);

    assert_eq!(
        vec3s!(1isize, 2isize, 3isize) != vec3s!(1isize, 2isize, 3isize),
        false
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize) != vec3s!(4isize, 3isize, 2isize),
        true
    );
    assert_eq!(
        vec3s!(1isize, 2isize, 3isize) != vec3s!(2isize, 2isize, 3isize),
        true
    );

    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize) != vec4s!(1isize, 2isize, 3isize, 4isize),
        false
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize) != vec4s!(4isize, 3isize, 2isize, 1isize),
        true
    );
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize) != vec4s!(2isize, 2isize, 2isize, 4isize),
        true
    );

    assert_eq!(vec2s!(1isize, 2isize).to_string(), "(1, 2)");
    assert_eq!(vec3s!(1isize, 2isize, 3isize).to_string(), "(1, 2, 3)");
    assert_eq!(
        vec4s!(1isize, 2isize, 3isize, 4isize).to_string(),
        "(1, 2, 3, 4)"
    );

    assert_eq!(format!("{:?}", vec2s!(1isize, 2isize)), "(1, 2)");
    assert_eq!(format!("{:?}", vec3s!(1isize, 2isize, 3isize)), "(1, 2, 3)");
    assert_eq!(
        format!("{:?}", vec4s!(1isize, 2isize, 3isize, 4isize)),
        "(1, 2, 3, 4)"
    );

    assert_eq!(vec2s!(1isize, 2isize).x, 1isize);
    assert_eq!(vec2s!(1isize, 2isize).y, 2isize);

    assert_eq!(vec3s!(1isize, 2isize, 3isize).x, 1isize);
    assert_eq!(vec3s!(1isize, 2isize, 3isize).y, 2isize);
    assert_eq!(vec3s!(1isize, 2isize, 3isize).z, 3isize);

    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).x, 1isize);
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).y, 2isize);
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).z, 3isize);
    assert_eq!(vec4s!(1isize, 2isize, 3isize, 4isize).w, 4isize);

    assert_eq!(&mut vec2s!(1isize, 2isize).x, &mut 1isize);
    assert_eq!(&mut vec2s!(1isize, 2isize).y, &mut 2isize);

    assert_eq!(&mut vec3s!(1isize, 2isize, 3isize).x, &mut 1isize);
    assert_eq!(&mut vec3s!(1isize, 2isize, 3isize).y, &mut 2isize);
    assert_eq!(&mut vec3s!(1isize, 2isize, 3isize).z, &mut 3isize);

    assert_eq!(&mut vec4s!(1isize, 2isize, 3isize, 4isize).x, &mut 1isize);
    assert_eq!(&mut vec4s!(1isize, 2isize, 3isize, 4isize).y, &mut 2isize);
    assert_eq!(&mut vec4s!(1isize, 2isize, 3isize, 4isize).z, &mut 3isize);
    assert_eq!(&mut vec4s!(1isize, 2isize, 3isize, 4isize).w, &mut 4isize);

    #[cfg(feature = "swizzle")]
    {
        assert_eq!(vec2s!(1isize, 2isize).xy(), vec2s!(1isize, 2isize));
        assert_eq!(vec2s!(1isize, 2isize).yx(), vec2s!(2isize, 1isize));
        assert_eq!(vec2s!(1isize, 2isize).yy(), vec2s!(2isize, 2isize));

        assert_eq!(vec3s!(1isize, 2isize, 3isize).xy(), vec2s!(1isize, 2isize));
        assert_eq!(vec3s!(1isize, 2isize, 3isize).xz(), vec2s!(1isize, 3isize));
        assert_eq!(vec3s!(1isize, 2isize, 3isize).zy(), vec2s!(3isize, 2isize));

        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).xy(),
            vec2s!(1isize, 2isize)
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).yw(),
            vec2s!(2isize, 4isize)
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).wy(),
            vec2s!(4isize, 2isize)
        );

        assert_eq!(vec2s!(1isize, 2isize).xyy(), vec3s!(1isize, 2isize, 2isize));
        assert_eq!(vec2s!(1isize, 2isize).yxy(), vec3s!(2isize, 1isize, 2isize));

        assert_eq!(
            vec3s!(1isize, 2isize, 3isize).xyz(),
            vec3s!(1isize, 2isize, 3isize)
        );
        assert_eq!(
            vec3s!(1isize, 2isize, 3isize).yxz(),
            vec3s!(2isize, 1isize, 3isize)
        );
        assert_eq!(
            vec3s!(1isize, 2isize, 3isize).zyx(),
            vec3s!(3isize, 2isize, 1isize)
        );

        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).xyz(),
            vec3s!(1isize, 2isize, 3isize)
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).yxz(),
            vec3s!(2isize, 1isize, 3isize)
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).zyx(),
            vec3s!(3isize, 2isize, 1isize)
        );

        assert_eq!(
            vec2s!(1isize, 2isize).xyyx(),
            vec4s!(1isize, 2isize, 2isize, 1isize)
        );
        assert_eq!(
            vec2s!(1isize, 2isize).yxyx(),
            vec4s!(2isize, 1isize, 2isize, 1isize)
        );
        assert_eq!(
            vec2s!(1isize, 2isize).yyxx(),
            vec4s!(2isize, 2isize, 1isize, 1isize)
        );

        assert_eq!(
            vec3s!(1isize, 2isize, 3isize).xyzx(),
            vec4s!(1isize, 2isize, 3isize, 1isize)
        );
        assert_eq!(
            vec3s!(1isize, 2isize, 3isize).yxzx(),
            vec4s!(2isize, 1isize, 3isize, 1isize)
        );
        assert_eq!(
            vec3s!(1isize, 2isize, 3isize).zyxx(),
            vec4s!(3isize, 2isize, 1isize, 1isize)
        );

        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).xyzw(),
            vec4s!(1isize, 2isize, 3isize, 4isize)
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).yxzw(),
            vec4s!(2isize, 1isize, 3isize, 4isize)
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).zyxw(),
            vec4s!(3isize, 2isize, 1isize, 4isize)
        );
        assert_eq!(
            vec4s!(1isize, 2isize, 3isize, 4isize).wyzx(),
            vec4s!(4isize, 2isize, 3isize, 1isize)
        );
    }
}

#[test]
#[should_panic]
fn test_vec2s_index_panic() {
    vec2!(1isize, 2isize)[2];
}

#[test]
#[should_panic]
fn test_vec3s_index_panic() {
    vec3!(1isize, 2isize, 3isize)[3];
}

#[test]
#[should_panic]
fn test_vec4s_index_panic() {
    vec4!(1isize, 2isize, 3isize, 4isize)[4];
}

#[test]
fn test_simd_int_fns() {
    assert_eq!(!vec2!(5isize, 7isize), vec2!(!5isize, !7isize));
    assert_eq!(
        !vec3!(5isize, 7isize, 9isize),
        vec3!(!5isize, !7isize, !9isize)
    );
    assert_eq!(
        !vec4!(5isize, 7isize, 9isize, 11isize),
        vec4!(!5isize, !7isize, !9isize, !11isize)
    );

    assert_eq!(
        vec2!(5isize, 7isize) + vec2!(9isize, 11isize),
        vec2!(5isize + 9isize, 7isize + 11isize)
    );
    assert_eq!(
        vec3!(5isize, 7isize, 9isize) + vec3!(11isize, 13isize, 15isize),
        vec3!(5isize + 11isize, 7isize + 13isize, 9isize + 15isize)
    );
    assert_eq!(
        vec4!(5isize, 7isize, 9isize, 11isize) + vec4!(13isize, 15isize, 17isize, 19isize),
        vec4!(
            5isize + 13isize,
            7isize + 15isize,
            9isize + 17isize,
            11isize + 19isize
        )
    );

    assert_eq!(
        vec2!(9isize, 11isize) - vec2!(5isize, 7isize),
        vec2!(9isize - 5isize, 11isize - 7isize)
    );
    assert_eq!(
        vec3!(9isize, 11isize, 13isize) - vec3!(5isize, 7isize, 9isize),
        vec3!(9isize - 5isize, 11isize - 7isize, 13isize - 9isize)
    );
    assert_eq!(
        vec4!(9isize, 11isize, 13isize, 15isize) - vec4!(5isize, 7isize, 9isize, 11isize),
        vec4!(
            9isize - 5isize,
            11isize - 7isize,
            13isize - 9isize,
            15isize - 11isize
        )
    );

    assert_eq!(
        vec2!(2isize, 4isize) * vec2!(3isize, 5isize),
        vec2!(2isize * 3isize, 4isize * 5isize)
    );
    assert_eq!(
        vec3!(2isize, 4isize, 6isize) * vec3!(3isize, 5isize, 7isize),
        vec3!(2isize * 3isize, 4isize * 5isize, 6isize * 7isize)
    );
    assert_eq!(
        vec4!(2isize, 4isize, 6isize, 8isize) * vec4!(3isize, 5isize, 7isize, 9isize),
        vec4!(
            2isize * 3isize,
            4isize * 5isize,
            6isize * 7isize,
            8isize * 9isize
        )
    );

    assert_eq!(
        vec2!(21isize, 23isize) / vec2!(4isize, 50isize),
        vec2!(21isize / 4isize, 23isize / 50isize)
    );
    assert_eq!(
        vec3!(21isize, 23isize, 25isize) / vec3!(4isize, 50isize, 3isize),
        vec3!(21isize / 4isize, 23isize / 50isize, 25isize / 3isize)
    );
    assert_eq!(
        vec4!(21isize, 23isize, 25isize, 27isize) / vec4!(4isize, 50isize, 3isize, 10isize),
        vec4!(
            21isize / 4isize,
            23isize / 50isize,
            25isize / 3isize,
            27isize / 10isize
        )
    );

    assert_eq!(
        vec2!(16isize, 19isize) / vec2!(5isize, 5isize),
        vec2!(16isize / 5isize, 19isize / 5isize)
    );
    assert_eq!(
        vec3!(16isize, 19isize, 22isize) / vec3!(5isize, 5isize, 5isize),
        vec3!(16isize / 5isize, 19isize / 5isize, 22isize / 5isize)
    );
    assert_eq!(
        vec4!(16isize, 19isize, 22isize, 25isize) / vec4!(5isize, 5isize, 5isize, 5isize),
        vec4!(
            16isize / 5isize,
            19isize / 5isize,
            22isize / 5isize,
            25isize / 5isize
        )
    );

    assert_eq!(
        vec2!(21isize, 23isize) % vec2!(4isize, 50isize),
        vec2!(21isize % 4isize, 23isize % 50isize)
    );
    assert_eq!(
        vec3!(21isize, 23isize, 25isize) % vec3!(4isize, 50isize, 3isize),
        vec3!(21isize % 4isize, 23isize % 50isize, 25isize % 3isize)
    );
    assert_eq!(
        vec4!(21isize, 23isize, 25isize, 27isize) % vec4!(4isize, 50isize, 3isize, 10isize),
        vec4!(
            21isize % 4isize,
            23isize % 50isize,
            25isize % 3isize,
            27isize % 10isize
        )
    );

    assert_eq!(
        vec2!(21isize, 23isize) & vec2!(4isize, 50isize),
        vec2!(21isize & 4isize, 23isize & 50isize)
    );
    assert_eq!(
        vec3!(21isize, 23isize, 25isize) & vec3!(4isize, 50isize, 3isize),
        vec3!(21isize & 4isize, 23isize & 50isize, 25isize & 3isize)
    );
    assert_eq!(
        vec4!(21isize, 23isize, 25isize, 27isize) & vec4!(4isize, 50isize, 3isize, 10isize),
        vec4!(
            21isize & 4isize,
            23isize & 50isize,
            25isize & 3isize,
            27isize & 10isize
        )
    );

    assert_eq!(
        vec2!(21isize, 23isize) | vec2!(4isize, 50isize),
        vec2!(21isize | 4isize, 23isize | 50isize)
    );
    assert_eq!(
        vec3!(21isize, 23isize, 25isize) | vec3!(4isize, 50isize, 3isize),
        vec3!(21isize | 4isize, 23isize | 50isize, 25isize | 3isize)
    );
    assert_eq!(
        vec4!(21isize, 23isize, 25isize, 27isize) | vec4!(4isize, 50isize, 3isize, 10isize),
        vec4!(
            21isize | 4isize,
            23isize | 50isize,
            25isize | 3isize,
            27isize | 10isize
        )
    );

    assert_eq!(
        vec2!(21isize, 23isize) ^ vec2!(4isize, 50isize),
        vec2!(21isize ^ 4isize, 23isize ^ 50isize)
    );
    assert_eq!(
        vec3!(21isize, 23isize, 25isize) ^ vec3!(4isize, 50isize, 3isize),
        vec3!(21isize ^ 4isize, 23isize ^ 50isize, 25isize ^ 3isize)
    );
    assert_eq!(
        vec4!(21isize, 23isize, 25isize, 27isize) ^ vec4!(4isize, 50isize, 3isize, 10isize),
        vec4!(
            21isize ^ 4isize,
            23isize ^ 50isize,
            25isize ^ 3isize,
            27isize ^ 10isize
        )
    );

    assert_eq!(Vec2::ZERO, vec2!(0isize, 0isize));
    assert_eq!(Vec3::ZERO, vec3!(0isize, 0isize, 0isize));
    assert_eq!(Vec4::ZERO, vec4!(0isize, 0isize, 0isize, 0isize));

    assert_eq!(Vec2::ONE, vec2!(1isize, 1isize));
    assert_eq!(Vec3::ONE, vec3!(1isize, 1isize, 1isize));
    assert_eq!(Vec4::ONE, vec4!(1isize, 1isize, 1isize, 1isize));

    assert_eq!(Vec2::X, vec2!(1isize, 0isize));
    assert_eq!(Vec3::Y, vec3!(0isize, 1isize, 0isize));
    assert_eq!(Vec4::Z, vec4!(0isize, 0isize, 1isize, 0isize));

    #[cfg(feature = "right")]
    {
        use ggmath::right::*;

        assert_eq!(Vec2::RIGHT, Vec2::X);
        assert_eq!(Vec3::RIGHT, Vec3::X);
        assert_eq!(Vec4::RIGHT, Vec4::X);
    }

    #[cfg(feature = "left")]
    {
        use ggmath::left::*;

        assert_eq!(Vec2::LEFT, Vec2::X);
        assert_eq!(Vec3::LEFT, Vec3::X);
        assert_eq!(Vec4::LEFT, Vec4::X);
    }

    #[cfg(feature = "backwards")]
    {
        use ggmath::backwards::*;

        assert_eq!(Vec3::BACKWARDS, Vec3::Z);
        assert_eq!(Vec4::BACKWARDS, Vec4::Z);
    }
}

macro_rules! test_simd_binop_edgecase {
    ( $(#[$attr:meta])* $vec2_fn:ident, $vec3_fn:ident, $vec4_fn:ident: $op:tt for $lhs:expr, $rhs:expr) => {
        #[test]
        $(#[$attr])*
        fn $vec2_fn() {
            assert_eq!(vec2!(1isize, $lhs) $op vec2!(1isize, $rhs), vec2!(1isize $op 1isize, $lhs $op $rhs));
        }

        #[test]
        $(#[$attr])*
        fn $vec3_fn() {
            assert_eq!(vec3!(1isize, $lhs, 1isize) $op vec3!(1isize, $rhs, 1isize), vec3!(1isize $op 1isize, $lhs $op $rhs, 1isize $op 1isize));
        }

        #[test]
        $(#[$attr])*
        fn $vec4_fn() {
            assert_eq!(vec4!(1isize, $lhs, 1isize, 1isize) $op vec4!(1isize, $rhs, 1isize, 1isize), vec4!(1isize $op 1isize, $lhs $op $rhs, 1isize $op 1isize, 1isize $op 1isize));
        }
    }
}

test_simd_binop_edgecase! {
    #[cfg_attr(debug_assertions, should_panic)]
    test_isizevec2_add_overflow,
    test_isizevec3_add_overflow,
    test_isizevec4_add_overflow:

    + for isize::MAX, 3
}
test_simd_binop_edgecase! {
    #[cfg_attr(debug_assertions, should_panic)]
    test_isizevec2_add_exact_overflow,
    test_isizevec3_add_exact_overflow,
    test_isizevec4_add_exact_overflow:

    + for isize::MAX, 1
}

test_simd_binop_edgecase! {
    #[cfg_attr(debug_assertions, should_panic)]
    test_isizevec2_sub_overflow,
    test_isizevec3_sub_overflow,
    test_isizevec4_sub_overflow:

    - for isize::MIN, 3
}
test_simd_binop_edgecase! {
    #[cfg_attr(debug_assertions, should_panic)]
    test_isizevec2_sub_exact_overflow,
    test_isizevec3_sub_exact_overflow,
    test_isizevec4_sub_exact_overflow:

    - for isize::MIN, 1
}

test_simd_binop_edgecase! {
    #[cfg_attr(debug_assertions, should_panic)]
    test_isizevec2_mul_overflow,
    test_isizevec3_mul_overflow,
    test_isizevec4_mul_overflow:

    * for isize::MAX, 3
}

test_simd_binop_edgecase! {
    #[should_panic]
    test_isizevec2_div_by_zero,
    test_isizevec3_div_by_zero,
    test_isizevec4_div_by_zero:

    / for 5isize, 0isize
}

test_simd_binop_edgecase! {
    #[should_panic]
    test_isizevec2_rem_by_zero,
    test_isizevec3_rem_by_zero,
    test_isizevec4_rem_by_zero:

    % for 5isize, 0isize
}

#[test]
fn test_nonsimd_int_fns() {
    assert_eq!(!vec2s!(5isize, 7isize), vec2s!(!5isize, !7isize));
    assert_eq!(
        !vec3s!(5isize, 7isize, 9isize),
        vec3s!(!5isize, !7isize, !9isize)
    );
    assert_eq!(
        !vec4s!(5isize, 7isize, 9isize, 11isize),
        vec4s!(!5isize, !7isize, !9isize, !11isize)
    );

    assert_eq!(
        vec2s!(5isize, 7isize) + vec2s!(9isize, 11isize),
        vec2s!(5isize + 9isize, 7isize + 11isize)
    );
    assert_eq!(
        vec3s!(5isize, 7isize, 9isize) + vec3s!(11isize, 13isize, 15isize),
        vec3s!(5isize + 11isize, 7isize + 13isize, 9isize + 15isize)
    );
    assert_eq!(
        vec4s!(5isize, 7isize, 9isize, 11isize) + vec4s!(13isize, 15isize, 17isize, 19isize),
        vec4s!(
            5isize + 13isize,
            7isize + 15isize,
            9isize + 17isize,
            11isize + 19isize
        )
    );

    assert_eq!(
        vec2s!(9isize, 11isize) - vec2s!(5isize, 7isize),
        vec2s!(9isize - 5isize, 11isize - 7isize)
    );
    assert_eq!(
        vec3s!(9isize, 11isize, 13isize) - vec3s!(5isize, 7isize, 9isize),
        vec3s!(9isize - 5isize, 11isize - 7isize, 13isize - 9isize)
    );
    assert_eq!(
        vec4s!(9isize, 11isize, 13isize, 15isize) - vec4s!(5isize, 7isize, 9isize, 11isize),
        vec4s!(
            9isize - 5isize,
            11isize - 7isize,
            13isize - 9isize,
            15isize - 11isize
        )
    );

    assert_eq!(
        vec2s!(2isize, 4isize) * vec2s!(3isize, 5isize),
        vec2s!(2isize * 3isize, 4isize * 5isize)
    );
    assert_eq!(
        vec3s!(2isize, 4isize, 6isize) * vec3s!(3isize, 5isize, 7isize),
        vec3s!(2isize * 3isize, 4isize * 5isize, 6isize * 7isize)
    );
    assert_eq!(
        vec4s!(2isize, 4isize, 6isize, 8isize) * vec4s!(3isize, 5isize, 7isize, 9isize),
        vec4s!(
            2isize * 3isize,
            4isize * 5isize,
            6isize * 7isize,
            8isize * 9isize
        )
    );

    assert_eq!(
        vec2s!(21isize, 23isize) / vec2s!(4isize, 50isize),
        vec2s!(21isize / 4isize, 23isize / 50isize)
    );
    assert_eq!(
        vec3s!(21isize, 23isize, 25isize) / vec3s!(4isize, 50isize, 3isize),
        vec3s!(21isize / 4isize, 23isize / 50isize, 25isize / 3isize)
    );
    assert_eq!(
        vec4s!(21isize, 23isize, 25isize, 27isize) / vec4s!(4isize, 50isize, 3isize, 10isize),
        vec4s!(
            21isize / 4isize,
            23isize / 50isize,
            25isize / 3isize,
            27isize / 10isize
        )
    );

    assert_eq!(
        vec2s!(16isize, 19isize) / vec2s!(5isize, 5isize),
        vec2s!(16isize / 5isize, 19isize / 5isize)
    );
    assert_eq!(
        vec3s!(16isize, 19isize, 22isize) / vec3s!(5isize, 5isize, 5isize),
        vec3s!(16isize / 5isize, 19isize / 5isize, 22isize / 5isize)
    );
    assert_eq!(
        vec4s!(16isize, 19isize, 22isize, 25isize) / vec4s!(5isize, 5isize, 5isize, 5isize),
        vec4s!(
            16isize / 5isize,
            19isize / 5isize,
            22isize / 5isize,
            25isize / 5isize
        )
    );

    assert_eq!(
        vec2s!(21isize, 23isize) % vec2s!(4isize, 50isize),
        vec2s!(21isize % 4isize, 23isize % 50isize)
    );
    assert_eq!(
        vec3s!(21isize, 23isize, 25isize) % vec3s!(4isize, 50isize, 3isize),
        vec3s!(21isize % 4isize, 23isize % 50isize, 25isize % 3isize)
    );
    assert_eq!(
        vec4s!(21isize, 23isize, 25isize, 27isize) % vec4s!(4isize, 50isize, 3isize, 10isize),
        vec4s!(
            21isize % 4isize,
            23isize % 50isize,
            25isize % 3isize,
            27isize % 10isize
        )
    );

    assert_eq!(
        vec2s!(21isize, 23isize) & vec2s!(4isize, 50isize),
        vec2s!(21isize & 4isize, 23isize & 50isize)
    );
    assert_eq!(
        vec3s!(21isize, 23isize, 25isize) & vec3s!(4isize, 50isize, 3isize),
        vec3s!(21isize & 4isize, 23isize & 50isize, 25isize & 3isize)
    );
    assert_eq!(
        vec4s!(21isize, 23isize, 25isize, 27isize) & vec4s!(4isize, 50isize, 3isize, 10isize),
        vec4s!(
            21isize & 4isize,
            23isize & 50isize,
            25isize & 3isize,
            27isize & 10isize
        )
    );

    assert_eq!(
        vec2s!(21isize, 23isize) | vec2s!(4isize, 50isize),
        vec2s!(21isize | 4isize, 23isize | 50isize)
    );
    assert_eq!(
        vec3s!(21isize, 23isize, 25isize) | vec3s!(4isize, 50isize, 3isize),
        vec3s!(21isize | 4isize, 23isize | 50isize, 25isize | 3isize)
    );
    assert_eq!(
        vec4s!(21isize, 23isize, 25isize, 27isize) | vec4s!(4isize, 50isize, 3isize, 10isize),
        vec4s!(
            21isize | 4isize,
            23isize | 50isize,
            25isize | 3isize,
            27isize | 10isize
        )
    );

    assert_eq!(
        vec2s!(21isize, 23isize) ^ vec2s!(4isize, 50isize),
        vec2s!(21isize ^ 4isize, 23isize ^ 50isize)
    );
    assert_eq!(
        vec3s!(21isize, 23isize, 25isize) ^ vec3s!(4isize, 50isize, 3isize),
        vec3s!(21isize ^ 4isize, 23isize ^ 50isize, 25isize ^ 3isize)
    );
    assert_eq!(
        vec4s!(21isize, 23isize, 25isize, 27isize) ^ vec4s!(4isize, 50isize, 3isize, 10isize),
        vec4s!(
            21isize ^ 4isize,
            23isize ^ 50isize,
            25isize ^ 3isize,
            27isize ^ 10isize
        )
    );

    assert_eq!(Vec2S::ZERO, vec2s!(0isize, 0isize));
    assert_eq!(Vec3S::ZERO, vec3s!(0isize, 0isize, 0isize));
    assert_eq!(Vec4S::ZERO, vec4s!(0isize, 0isize, 0isize, 0isize));

    assert_eq!(Vec2S::ONE, vec2s!(1isize, 1isize));
    assert_eq!(Vec3S::ONE, vec3s!(1isize, 1isize, 1isize));
    assert_eq!(Vec4S::ONE, vec4s!(1isize, 1isize, 1isize, 1isize));

    assert_eq!(Vec2S::X, vec2s!(1isize, 0isize));
    assert_eq!(Vec3S::Y, vec3s!(0isize, 1isize, 0isize));
    assert_eq!(Vec4S::Z, vec4s!(0isize, 0isize, 1isize, 0isize));

    #[cfg(feature = "right")]
    {
        use ggmath::right::*;

        assert_eq!(Vec2S::RIGHT, Vec2S::X);
        assert_eq!(Vec3S::RIGHT, Vec3S::X);
        assert_eq!(Vec4S::RIGHT, Vec4S::X);
    }

    #[cfg(feature = "left")]
    {
        use ggmath::left::*;

        assert_eq!(Vec2S::LEFT, Vec2S::X);
        assert_eq!(Vec3S::LEFT, Vec3S::X);
        assert_eq!(Vec4S::LEFT, Vec4S::X);
    }

    #[cfg(feature = "backwards")]
    {
        use ggmath::backwards::*;

        assert_eq!(Vec3S::BACKWARDS, Vec3S::Z);
        assert_eq!(Vec4S::BACKWARDS, Vec4S::Z);
    }
}

macro_rules! test_nonsimd_binop_edgecase {
    ( $(#[$attr:meta])* $vec2_fn:ident, $vec3_fn:ident, $vec4_fn:ident: $op:tt for $lhs:expr, $rhs:expr) => {
        #[test]
        $(#[$attr])*
        fn $vec2_fn() {
            assert_eq!(vec2s!(1isize, $lhs) $op vec2s!(1isize, $rhs), vec2s!(1isize $op 1isize, $lhs $op $rhs));
        }

        #[test]
        $(#[$attr])*
        fn $vec3_fn() {
            assert_eq!(vec3s!(1isize, $lhs, 1isize) $op vec3s!(1isize, $rhs, 1isize), vec3s!(1isize $op 1isize, $lhs $op $rhs, 1isize $op 1isize));
        }

        #[test]
        $(#[$attr])*
        fn $vec4_fn() {
            assert_eq!(vec4s!(1isize, $lhs, 1isize, 1isize) $op vec4s!(1isize, $rhs, 1isize, 1isize), vec4s!(1isize $op 1isize, $lhs $op $rhs, 1isize $op 1isize, 1isize $op 1isize));
        }
    }
}

test_nonsimd_binop_edgecase! {
    #[cfg_attr(debug_assertions, should_panic)]
    test_isizevec2s_add_overflow,
    test_isizevec3s_add_overflow,
    test_isizevec4s_add_overflow:

    + for isize::MAX, 3
}
test_nonsimd_binop_edgecase! {
    #[cfg_attr(debug_assertions, should_panic)]
    test_isizevec2s_add_exact_overflow,
    test_isizevec3s_add_exact_overflow,
    test_isizevec4s_add_exact_overflow:

    + for isize::MAX, 1
}

test_nonsimd_binop_edgecase! {
    #[cfg_attr(debug_assertions, should_panic)]
    test_isizevec2s_sub_overflow,
    test_isizevec3s_sub_overflow,
    test_isizevec4s_sub_overflow:

    - for isize::MIN, 3
}
test_nonsimd_binop_edgecase! {
    #[cfg_attr(debug_assertions, should_panic)]
    test_isizevec2s_sub_exact_overflow,
    test_isizevec3s_sub_exact_overflow,
    test_isizevec4s_sub_exact_overflow:

    - for isize::MIN, 1
}

test_nonsimd_binop_edgecase! {
    #[cfg_attr(debug_assertions, should_panic)]
    test_isizevec2s_mul_overflow,
    test_isizevec3s_mul_overflow,
    test_isizevec4s_mul_overflow:

    * for isize::MAX, 3
}

test_nonsimd_binop_edgecase! {
    #[should_panic]
    test_isizevec2s_div_by_zero,
    test_isizevec3s_div_by_zero,
    test_isizevec4s_div_by_zero:

    / for 5isize, 0isize
}

test_nonsimd_binop_edgecase! {
    #[should_panic]
    test_isizevec2s_rem_by_zero,
    test_isizevec3s_rem_by_zero,
    test_isizevec4s_rem_by_zero:

    % for 5isize, 0isize
}
