// This file was generated by an associated codegen crate.
// To modify this file, modify the source code of the associated codegen crate.

mod bool;
mod f32;
mod f64;
mod i128;
mod i16;
mod i32;
mod i64;
mod i8;
mod isize;
mod u128;
mod u16;
mod u32;
mod u64;
mod u8;
mod usize;
