[package]
name = "direction_constants"
version = "0.1.0"
edition = "2024"

[dependencies]
ggmath = { path = "../../", features = [
    "right",
    "left",
    "up",
    "down",
    "forwards",
    "backwards",
] }
