// This file was generated by an associated codegen crate.
// To modify this file, modify the source code of the associated codegen crate.

use ggmath::*;

const _: () = assert!(size_of::<Vec2P<i64>>() == size_of::<[i64; 2]>());
const _: () = assert!(size_of::<Vec3P<i64>>() == size_of::<[i64; 3]>());
const _: () = assert!(size_of::<Vec4P<i64>>() == size_of::<[i64; 4]>());
