// This file was generated by an associated codegen crate.
// To modify this file, modify the source code of the associated codegen crate.

use ggmath::*;

const _: () = assert!(size_of::<Vec2P<u16>>() == size_of::<[u16; 2]>());
const _: () = assert!(size_of::<Vec3P<u16>>() == size_of::<[u16; 3]>());
const _: () = assert!(size_of::<Vec4P<u16>>() == size_of::<[u16; 4]>());
