// This file was generated by an associated codegen crate.
// To modify this file, modify the source code of the associated codegen crate.

use ggmath::*;

const _: () = assert!(size_of::<Vec2P<u32>>() == size_of::<[u32; 2]>());
const _: () = assert!(size_of::<Vec3P<u32>>() == size_of::<[u32; 3]>());
const _: () = assert!(size_of::<Vec4P<u32>>() == size_of::<[u32; 4]>());
