// This file was automatically generated by ggmath's codegen tool.
// Do not modify this file directly!

use crate::{ElementOfVector, NonSimd, Simdness, Vector};

impl<const N: usize, S: Simdness> Vector<N, f32, S>
where
    f32: F32VectorApi<N, S>,
{
    /// Returns a vector with the largest integer less than or equal to each element of `self`.
    #[inline(always)]
    pub fn floor(self) -> Self {
        f32::vec_floor(self)
    }

    /// Returns a vector with the smallest integer greater than or equal to each element of `self`.
    #[inline(always)]
    pub fn ceil(self) -> Self {
        f32::vec_ceil(self)
    }

    /// Returns a vector with the nearest integer to each element of `self`.
    /// If an element is half-way between two integers, round away from `0.0`.
    #[inline(always)]
    pub fn round(self) -> Self {
        f32::vec_round(self)
    }

    /// Returns a vector with the integer part of each element of `self`.
    /// This means that each element is rounded towards zero.
    #[inline(always)]
    pub fn trunc(self) -> Self {
        f32::vec_trunc(self)
    }

    /// Returns a vector with the fractional part of each element of `self`.
    /// This is equivalent to `self - self.trunc()`.
    #[inline(always)]
    pub fn fract(self) -> Self {
        f32::vec_fract(self)
    }

    /// Fused multiply-add. Computes `(self * a) + b` with only one rounding error,
    /// yielding a more accurate result than an unfused multiply-add.
    ///
    /// Using `mul_add` *may* be more performant than an unfused multiply-add
    /// if the target architecture has a dedicated `fma` CPU instruction.
    /// However, this is not always true, and will be heavily dependent on designing
    /// algorithms with specific target hardware in mind.
    #[inline(always)]
    pub fn mul_add(self, a: Self, b: Self) -> Self {
        f32::vec_mul_add(self, a, b)
    }

    /// Calculates Euclidean division, the matching method for `rem_euclid`.
    #[inline(always)]
    pub fn div_euclid(self, rhs: Self) -> Self {
        f32::vec_div_euclid(self, rhs)
    }

    /// Calculates the least nonnegative remainder of `self (mod rhs)`.
    #[inline(always)]
    pub fn rem_euclid(self, rhs: Self) -> Self {
        f32::vec_rem_euclid(self, rhs)
    }

    /// Returns a vector with the square root of each element of `self`.
    ///
    /// Returns `NaN` for elements that are negative numbers other than `-0.0`,
    /// but only for those elements.
    #[inline(always)]
    pub fn sqrt(self) -> Self {
        f32::vec_sqrt(self)
    }

    /// Returns a vector with the sine of each element of `self`.
    #[inline(always)]
    pub fn sin(self) -> Self {
        f32::vec_sin(self)
    }

    /// Returns a vector with the cosine of each element of `self`.
    #[inline(always)]
    pub fn cos(self) -> Self {
        f32::vec_cos(self)
    }

    /// Returns a vector with the tangent of each element of `self`.
    #[inline(always)]
    pub fn tan(self) -> Self {
        f32::vec_tan(self)
    }

    /// Returns a vector with the arcsine of each element of `self`.
    #[inline(always)]
    pub fn asin(self) -> Self {
        f32::vec_asin(self)
    }

    /// Returns a vector with the arccosine of each element of `self`.
    #[inline(always)]
    pub fn acos(self) -> Self {
        f32::vec_acos(self)
    }

    /// Returns a vector with the arctangent of each element of `self`.
    #[inline(always)]
    pub fn atan(self) -> Self {
        f32::vec_atan(self)
    }

    /// Returns a vector with the reciprocal of each element of `self`, `1.0 / self`.
    #[inline(always)]
    pub fn recip(self) -> Self {
        f32::vec_recip(self)
    }

    /// Returns a vector with the maximum of each element of `self` and `other`.
    #[inline(always)]
    pub fn max(self, other: Self) -> Self {
        f32::vec_max(self, other)
    }

    /// Returns a vector with the minimum of each element of `self` and `other`.
    #[inline(always)]
    pub fn min(self, other: Self) -> Self {
        f32::vec_min(self, other)
    }

    /// Returns a vector with the midpoint of each element of `self` and `other`.
    #[inline(always)]
    pub fn midpoint(self, other: Self) -> Self {
        f32::vec_midpoint(self, other)
    }

    /// Returns a vector with the clamp of each element of `self` between each element of `min` and `max`.
    ///
    /// In release mode, semantics may differ if `min` is greater than `max` in any element,
    /// or if `min` or `max` is `NaN`.
    ///
    /// # Panics
    ///
    /// In debug mode, this will panic if `min` is greater than `max` in any element,
    /// or if `min` or `max` is `NaN`.
    #[inline(always)]
    pub fn clamp(self, min: Self, max: Self) -> Self {
        f32::vec_clamp(self, min, max)
    }

    /// Returns a vector with the absolute value of each element of `self`.
    #[inline(always)]
    pub fn abs(self) -> Self {
        f32::vec_abs(self)
    }

    /// Returns a vector with elements representing the sign of each element of `self`.
    ///
    /// - `1.0` if an element is positive, `+0.0` or `INFINITY`
    /// - `-1.0` if an element is negative, `-0.0` or `NEG_INFINITY`
    /// - `NaN` if the element is `NaN`.
    #[inline(always)]
    pub fn signum(self) -> Self {
        f32::vec_signum(self)
    }

    /// Returns a vector with the signs of `sign` and the magnitudes of `self`.
    ///
    /// Sign of `0.0` is considered positive.
    #[inline(always)]
    pub fn copysign(self, sign: Self) -> Self {
        f32::vec_copysign(self, sign)
    }

    /// Returns the sum of all elements of `self`.
    /// Equivalent to `self.x + self.y + ..`.
    #[inline(always)]
    pub fn sum(self) -> f32 {
        f32::vec_sum(self)
    }

    /// Returns the product of all elements of `self`.
    /// Equivalent to `self.x * self.y * ..`.
    #[inline(always)]
    pub fn product(self) -> f32 {
        f32::vec_product(self)
    }
}

/// TODO: make this pub(crate)
pub trait F32VectorApi<const N: usize, S: Simdness>
where
    f32: ElementOfVector<N, S>,
{
    /// TODO: make this pub(crate)
    fn vec_floor(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::floor)
    }

    /// TODO: make this pub(crate)
    fn vec_ceil(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::ceil)
    }

    /// TODO: make this pub(crate)
    fn vec_round(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::round)
    }

    /// TODO: make this pub(crate)
    fn vec_trunc(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::trunc)
    }

    /// TODO: make this pub(crate)
    fn vec_fract(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::fract)
    }

    /// TODO: make this pub(crate)
    fn vec_mul_add(
        vec: Vector<N, f32, S>,
        a: Vector<N, f32, S>,
        b: Vector<N, f32, S>,
    ) -> Vector<N, f32, S> {
        vec.zip(a).zip(b).map(|((x, a), b)| f32::mul_add(x, a, b))
    }

    /// TODO: make this pub(crate)
    fn vec_div_euclid(vec: Vector<N, f32, S>, rhs: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.zip(rhs).map(|(x, rhs)| f32::div_euclid(x, rhs))
    }

    /// TODO: make this pub(crate)
    fn vec_rem_euclid(vec: Vector<N, f32, S>, rhs: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.zip(rhs).map(|(x, rhs)| f32::rem_euclid(x, rhs))
    }

    /// TODO: make this pub(crate)
    fn vec_sqrt(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::sqrt)
    }

    /// TODO: make this pub(crate)
    fn vec_sin(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::sin)
    }

    /// TODO: make this pub(crate)
    fn vec_cos(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::cos)
    }

    /// TODO: make this pub(crate)
    fn vec_tan(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::tan)
    }

    /// TODO: make this pub(crate)
    fn vec_asin(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::asin)
    }

    /// TODO: make this pub(crate)
    fn vec_acos(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::acos)
    }

    /// TODO: make this pub(crate)
    fn vec_atan(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::atan)
    }

    /// TODO: make this pub(crate)
    fn vec_recip(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::recip)
    }

    /// TODO: make this pub(crate)
    fn vec_max(vec: Vector<N, f32, S>, other: Vector<N, f32, S>) -> Vector<N, f32, S> {
        debug_assert!(vec.iter().all(|x| !x.is_nan()));
        debug_assert!(other.iter().all(|x| !x.is_nan()));

        vec.zip(other).map(|(x, other)| f32::max(x, other))
    }

    /// TODO: make this pub(crate)
    fn vec_min(vec: Vector<N, f32, S>, other: Vector<N, f32, S>) -> Vector<N, f32, S> {
        debug_assert!(vec.iter().all(|x| !x.is_nan()));
        debug_assert!(other.iter().all(|x| !x.is_nan()));

        vec.zip(other).map(|(x, other)| f32::min(x, other))
    }

    /// TODO: make this pub(crate)
    fn vec_midpoint(vec: Vector<N, f32, S>, other: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.zip(other).map(|(x, other)| f32::midpoint(x, other))
    }

    /// TODO: make this pub(crate)
    fn vec_clamp(
        vec: Vector<N, f32, S>,
        min: Vector<N, f32, S>,
        max: Vector<N, f32, S>,
    ) -> Vector<N, f32, S> {
        debug_assert!(min.zip(max).iter().all(|(min, max)| min <= max));
        debug_assert!(min.iter().all(|x| !x.is_nan()));
        debug_assert!(max.iter().all(|x| !x.is_nan()));

        vec.zip(min)
            .zip(max)
            .map(|((x, min), max)| f32::clamp(x, min, max))
    }

    /// TODO: make this pub(crate)
    fn vec_abs(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::abs)
    }

    /// TODO: make this pub(crate)
    fn vec_signum(vec: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.map(f32::signum)
    }

    /// TODO: make this pub(crate)
    fn vec_copysign(vec: Vector<N, f32, S>, sign: Vector<N, f32, S>) -> Vector<N, f32, S> {
        vec.zip(sign).map(|(x, sign)| f32::copysign(x, sign))
    }

    /// TODO: make this pub(crate)
    fn vec_sum(vec: Vector<N, f32, S>) -> f32 {
        vec.iter().sum()
    }

    /// TODO: make this pub(crate)
    fn vec_product(vec: Vector<N, f32, S>) -> f32 {
        vec.iter().product()
    }
}

impl<const N: usize> F32ElementOfVector<N, NonSimd> for f32 {}
