[package]
edition = "2021"
name    = "ggmath_proc_macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
derive-syn-parse = "0.2.0"
proc-macro2      = "1.0.86"
quote            = "1.0.37"
syn              = { version = "2.0.79", features = [ "extra-traits", "full" ] }
