name: Verify

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ${{ matrix.config.os }}
    env:
      RUSTFLAGS: -D warnings ${{ matrix.config.rustflags }}
    strategy:
      matrix:
        config:
        - { target: i686-pc-windows-msvc, os: windows-latest, rustflags: "" }
        - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, rustflags: "" }
        - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, rustflags: "-C target-feature=+ssse3,+sse4.1,+sse4.2,+avx2,+fma" }
        - { target: aarch64-apple-darwin, os: macos-latest, rustflags: "" }
        - { target: wasm32-wasip1, os: ubuntu-latest, rustflags: "-C target-feature=+simd128" }
        - { target: wasm32-wasip1, os: ubuntu-latest, rustflags: "-C target-feature=-simd128" }
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "1.95.0"
        target:  ${{ matrix.config.target }}
        components: clippy
    - uses: Swatinem/rust-cache@master

    - name: Clippy
      run: cargo clippy --all-targets --target ${{ matrix.config.target }}

    - name: Clippy with Libm
      run: cargo clippy --all-targets --features libm --target ${{ matrix.config.target }}

    - name: Clippy with optional dependencies
      run: cargo clippy --all-targets --features "bytemuck fixed mint rand serde wide" --target ${{ matrix.config.target }}

    - name: Clippy with Libm and optional dependencies
      run: cargo clippy --all-targets --all-features --target ${{ matrix.config.target }}

  test:
    runs-on: ${{ matrix.config.os }}
    env:
      RUSTFLAGS: -D warnings ${{ matrix.config.rustflags }} ${{ matrix.command.rustflags }}
      CARGO_TARGET_WASM32_WASIP1_RUNNER: wasmtime run --dir .
      CARGO_TARGET_WASM32_WASIP1_RUSTFLAGS: -D warnings ${{ matrix.config.rustflags }} ${{ matrix.command.rustflags }}
    strategy:
      matrix:
        config:
        - { target: i686-pc-windows-msvc, os: windows-latest, rustflags: "" }
        - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, rustflags: "" }
        - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, rustflags: "-C target-feature=+ssse3,+sse4.1,+sse4.2,+avx2,+fma" }
        - { target: aarch64-apple-darwin, os: macos-latest, rustflags: "" }
        - { target: wasm32-wasip1, os: ubuntu-latest, rustflags: "-C target-feature=+simd128" }
        - { target: wasm32-wasip1, os: ubuntu-latest, rustflags: "-C target-feature=-simd128" }

        command:
        - rustflags: -C debug-assertions=off -C overflow-checks=off
          args: --features "bytemuck fixed mint rand serde wide"

        - rustflags: -C debug-assertions=on -C overflow-checks=on
          args: --all-features

        exclude:
          - config: { target: wasm32-wasip1 }
          - command: { rustflags: -C debug-assertions=on -C overflow-checks=on }

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "1.95.0"
        target: ${{ matrix.config.target }}
        components: clippy
    - uses: Swatinem/rust-cache@master

    - name: Install Wasmtime
      if: matrix.config.target == 'wasm32-wasip1'
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash -s -- --version v39.0.1
        echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

    - name: Cargo Test
      run: cargo test ${{ matrix.command.args }} --target ${{ matrix.config.target }}  -- --nocapture

  fmt_and_doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.95.0
        components: rustfmt
    - uses: Swatinem/rust-cache@master

    - name: Cargo Fmt
      run: cargo fmt --check --all

    - name: Doc
      run: cargo doc --no-deps

    - name: Doc with optional dependencies
      run: cargo doc --no-deps --features "bytemuck fixed mint rand serde wide"
