name: Verify

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ${{ matrix.rust.os }}
    env:
      RUSTFLAGS: -D warnings
    strategy:
      matrix:
        rust:
        # x86
        - { target: i686-pc-windows-msvc, os: windows-latest }
        # x86_64
        - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "1.95.0"
        target:  ${{ matrix.rust.target }}
        components: clippy
    - uses: Swatinem/rust-cache@master

    - name: Clippy
      run: cargo clippy --all-targets --target ${{ matrix.rust.target }}

    - name: Clippy with Libm
      run: cargo clippy --all-targets --features libm --target ${{ matrix.rust.target }}

    - name: Clippy with optional dependencies
      run: cargo clippy --all-targets --features "bytemuck fixed mint rand serde wide" --target ${{ matrix.rust.target }}

    - name: Clippy with Libm and optional dependencies
      run: cargo clippy --all-targets --all-features --target ${{ matrix.rust.target }}

    - name: Test with optional dependencies
      env:
        RUSTFLAGS: -D warnings -C debug-assertions=off -C overflow-checks=off
      run: cargo test --features "bytemuck fixed mint rand serde wide" --target ${{ matrix.rust.target }}

    - name: Test with debug assertions, Libm and with optional dependencies
      env:
        RUSTFLAGS: -D warnings -C debug-assertions=on -C overflow-checks=on
      run: cargo test --all-features --target ${{ matrix.rust.target }}

    - name: Test with SSE4.1, SSE4.2, SSSE3 and optional dependencies
      if: matrix.rust.os == 'ubuntu-latest' && matrix.rust.target == 'x86_64-unknown-linux-gnu'
      env:
        RUSTFLAGS: -D warnings -C target-feature=+sse4.1,+sse4.2,+ssse3 -C debug-assertions=off -C overflow-checks=off
      run: cargo test --features "bytemuck fixed mint rand serde wide" --target ${{ matrix.rust.target }}

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.95.0
    - uses: Swatinem/rust-cache@master

    - name: Doc
      run: cargo doc --no-deps

    - name: Doc with optional dependencies
      run: cargo doc --no-deps --features "bytemuck fixed mint rand serde wide"
